# Generated by Django 4.2.1 on 2023-07-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_postlikessharesmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminDetails',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100, null=True, unique=True)),
                ('password', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'admin_details_tbl',
                'ordering': ('admin_id',),
            },
        ),
    ]
