# Generated by Django 4.2.1 on 2023-07-13 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0005_postcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCommentReplys',
            fields=[
                ('reply_id', models.AutoField(primary_key=True, serialize=False)),
                ('reply_date', models.DateField()),
                ('reply_mesage', models.CharField(max_length=255)),
                ('comment_photo', models.CharField(max_length=255)),
                ('flag', models.IntegerField(default=0)),
                ('comment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentreplys', to='MyApp.postcomment')),
                ('reply_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentreplys', to='MyApp.userdetailsmodel')),
            ],
            options={
                'db_table': 'tblpost_comment_replys',
                'ordering': ('reply_id',),
            },
        ),
    ]
