# Generated by Django 4.2.1 on 2023-07-13 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0008_likessharespostmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOpeningsModel',
            fields=[
                ('opening_id', models.AutoField(primary_key=True, serialize=False)),
                ('opening_date', models.DateField()),
                ('company_name', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('experience_required', models.CharField(max_length=255)),
                ('job_description', models.CharField(max_length=255)),
                ('is_active', models.ImageField(default=0, upload_to='')),
                ('flag', models.ImageField(default=0, upload_to='')),
                ('opening_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job', to='MyApp.userdetailsmodel')),
            ],
            options={
                'db_table': 'tbljob_openings',
                'ordering': ('opening_id',),
            },
        ),
    ]
