# Generated by Django 4.2.1 on 2023-07-13 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0009_jobopeningsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentPostModel',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_date', models.DateField()),
                ('comment_message', models.CharField(max_length=255)),
                ('comment_photo', models.CharField(max_length=255)),
                ('flag', models.IntegerField(default=0)),
                ('comment_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentpost', to='MyApp.userdetailsmodel')),
                ('opening_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentpost', to='MyApp.jobopeningsmodel')),
            ],
            options={
                'db_table': 'post_comments_tbl',
                'ordering': ('comment_id',),
            },
        ),
    ]
