# Generated by Django 4.2.1 on 2023-07-13 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0010_commentpostmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentPostReplyModel',
            fields=[
                ('reply_id', models.AutoField(primary_key=True, serialize=False)),
                ('reply_date', models.DateField()),
                ('reply_mesage', models.CharField(max_length=255)),
                ('comment_photo', models.CharField(max_length=255)),
                ('flag', models.IntegerField(default=0)),
                ('comment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replypost', to='MyApp.commentpostmodel')),
                ('reply_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replypost', to='MyApp.userdetailsmodel')),
            ],
            options={
                'db_table': 'post_comment_replys_tbl',
                'ordering': ('reply_id',),
            },
        ),
    ]
