# Generated by Django 4.2.1 on 2023-07-13 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0011_commentpostreplymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostDislikeModel',
            fields=[
                ('like_dislike_id', models.AutoField(primary_key=True, serialize=False)),
                ('like_dislike_date', models.DateField()),
                ('is_like', models.IntegerField(default=0)),
                ('flag', models.IntegerField(default=0)),
                ('like_dislike_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postdislike', to='MyApp.userdetailsmodel')),
                ('opening_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postdislike', to='MyApp.jobopeningsmodel')),
            ],
            options={
                'db_table': 'post_likes_dislikes_tbl',
                'ordering': ('like_dislike_id',),
            },
        ),
    ]
