# Generated by Django 4.2.1 on 2023-07-13 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0012_postdislikemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostLikesSharesTableModel',
            fields=[
                ('share_id', models.AutoField(primary_key=True, serialize=False)),
                ('share_date', models.DateField()),
                ('flag', models.IntegerField(default=0)),
                ('opening_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likesharepost', to='MyApp.jobopeningsmodel')),
                ('share_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likesharepost', to='MyApp.userdetailsmodel')),
            ],
            options={
                'db_table': 'post_likes_shares_tbl',
                'ordering': ('share_id',),
            },
        ),
    ]
