# Generated by Django 4.2.1 on 2023-07-13 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0013_postlikessharestablemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateModel',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('update_date', models.DateField()),
                ('update_title', models.CharField(max_length=100)),
                ('update_desription', models.CharField(max_length=255)),
                ('flag', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'tbl_update',
                'ordering': ('update_id',),
            },
        ),
    ]
