# Generated by Django 4.2.1 on 2023-07-13 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MyApp', '0015_delete_admindetails_remove_citysmodel_state_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=100, null=True, unique=True)),
                ('flag', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'tbltopics',
                'ordering': ('topic_name',),
            },
        ),
    ]
