# Generated by Django 4.2.1 on 2023-07-13 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0016_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_name', models.CharField(max_length=100, null=True)),
                ('flag', models.IntegerField(default=0)),
                ('topic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='MyApp.topicsmodel')),
            ],
            options={
                'db_table': 'tbltopiccontents',
                'ordering': ('content_name',),
            },
        ),
    ]
