# Generated by Django 4.2.1 on 2023-07-13 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0019_statesmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitysModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100, null=True)),
                ('flag', models.IntegerField(default=0)),
                ('state_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cityname', to='MyApp.statesmodel')),
            ],
            options={
                'db_table': 'tblcitys',
                'ordering': ('city_name',),
            },
        ),
    ]
