# Generated by Django 4.2.1 on 2023-07-13 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0020_citysmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualificationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(max_length=100, null=True, unique=True)),
                ('flag', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'tblqualifications',
                'ordering': ('qualification',),
            },
        ),
        migrations.CreateModel(
            name='LocationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=100, null=True)),
                ('flag', models.IntegerField(default=0)),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='MyApp.citysmodel')),
            ],
            options={
                'db_table': 'tbllocations',
                'ordering': ('location_name',),
            },
        ),
    ]
