# Generated by Django 4.2.1 on 2023-07-13 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0021_qualificationmodel_locationmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100, null=True)),
                ('flag', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'tbldesignations',
                'ordering': ('designation',),
            },
        ),
        migrations.CreateModel(
            name='GenderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=100, null=True)),
                ('flag', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'tblgenders',
                'ordering': ('gender',),
            },
        ),
        migrations.CreateModel(
            name='RoleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100, null=True)),
                ('flag', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'tblrole',
                'ordering': ('role',),
            },
        ),
        migrations.CreateModel(
            name='SpecializationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=100, null=True, unique=True)),
                ('flag', models.IntegerField(default=0)),
                ('qualification_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special', to='MyApp.qualificationmodel')),
            ],
            options={
                'db_table': 'tblspecializations',
                'ordering': ('specialization',),
            },
        ),
    ]
