# Generated by Django 4.2.1 on 2023-07-13 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0022_designationmodel_gendermodel_rolemodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetailsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('local_address', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('joining_date', models.DateField()),
                ('user_photo', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=20)),
                ('emial_address', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=100)),
                ('is_premium', models.IntegerField(default=0)),
                ('password', models.CharField(max_length=100)),
                ('flag', models.IntegerField(default=0)),
                ('gender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userdetails', to='MyApp.gendermodel')),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userdetails', to='MyApp.locationmodel')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userdetails', to='MyApp.rolemodel')),
            ],
            options={
                'db_table': 'tbluser_details',
                'ordering': ('first_name',),
            },
        ),
    ]
