# Generated by Django 4.2.1 on 2023-07-13 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0023_userdetailsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualiModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=100)),
                ('passing_year', models.ImageField(upload_to='')),
                ('medium', models.CharField(max_length=100)),
                ('percentage', models.FloatField()),
                ('flag', models.IntegerField(default=0)),
                ('specialization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifiaction', to='MyApp.specializationmodel')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifiaction', to='MyApp.userdetailsmodel')),
            ],
            options={
                'db_table': 'tbluser_qualifications',
                'ordering': ('university',),
            },
        ),
    ]
