# Generated by Django 4.2.1 on 2023-07-13 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0025_userprofessionalexpertisemodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_date', models.DateField()),
                ('post_title', models.CharField(max_length=100)),
                ('post_description', models.CharField(max_length=255)),
                ('photo', models.CharField(max_length=255)),
                ('is_active', models.IntegerField(default=0)),
                ('flag', models.IntegerField(default=0)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userpost', to='MyApp.userdetailsmodel')),
            ],
            options={
                'db_table': 'tbluser_posts',
                'ordering': ('post_date',),
            },
        ),
        migrations.CreateModel(
            name='PostCommentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_date', models.DateField()),
                ('comment_message', models.CharField(max_length=255)),
                ('comment_photo', models.CharField(max_length=255)),
                ('flag', models.IntegerField(default=0)),
                ('comment_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postcomments', to='MyApp.userdetailsmodel')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postcomment', to='MyApp.userpostmodel')),
            ],
            options={
                'db_table': 'tbpost_comments',
                'ordering': ('comment_date',),
            },
        ),
    ]
