# Generated by Django 4.2.1 on 2023-07-13 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0026_userpostmodel_postcommentsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCommentReplymodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_date', models.DateField()),
                ('reply_mesage', models.CharField(max_length=100)),
                ('comment_photo', models.CharField(max_length=100)),
                ('flag', models.IntegerField(default=0)),
                ('comment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentreply', to='MyApp.postcommentsmodel')),
                ('reply_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentreply', to='MyApp.userdetailsmodel')),
            ],
            options={
                'db_table': 'tbpost_comment_replys',
                'ordering': ('reply_mesage',),
            },
        ),
    ]
