# Generated by Django 4.2.1 on 2023-07-13 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0027_postcommentreplymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100, null=True, unique=True)),
                ('password', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'admin_details_tbl',
                'ordering': ('user_name',),
            },
        ),
        migrations.CreateModel(
            name='PostLikesSharesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_date', models.DateField()),
                ('flag', models.IntegerField(default=0)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likesshares', to='MyApp.userpostmodel')),
                ('share_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likesshares', to='MyApp.userdetailsmodel')),
            ],
            options={
                'db_table': 'tblpost_likes_shares',
                'ordering': ('share_date',),
            },
        ),
        migrations.CreateModel(
            name='PostLikesDislikesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_dislike_date', models.DateField()),
                ('is_like', models.IntegerField(default=0)),
                ('flag', models.IntegerField(default=0)),
                ('like_dislike_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likedislike', to='MyApp.userdetailsmodel')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likedislike', to='MyApp.userpostmodel')),
            ],
            options={
                'db_table': 'tbl_post_dis_likes',
                'ordering': ('like_dislike_date',),
            },
        ),
        migrations.CreateModel(
            name='CodePostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('question', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('is_active', models.IntegerField(default=0)),
                ('flag', models.IntegerField(default=0)),
                ('content_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codepost', to='MyApp.contentmodel')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codepost', to='MyApp.userdetailsmodel')),
            ],
            options={
                'db_table': 'tblcode_post_s',
                'ordering': ('question',),
            },
        ),
    ]
