# Generated by Django 4.2.1 on 2023-07-13 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0028_admindetails_postlikessharesmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_date', models.DateField()),
                ('comment_message', models.CharField(max_length=255)),
                ('comment_photo', models.CharField(max_length=255)),
                ('flag', models.IntegerField(default=0)),
                ('comment_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentspost', to='MyApp.userdetailsmodel')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentspost', to='MyApp.codepostmodel')),
            ],
            options={
                'db_table': 'tbpostcomments',
                'ordering': ('comment_date',),
            },
        ),
        migrations.CreateModel(
            name='PostLikesDislikesTBModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_dislike_date', models.DateField()),
                ('is_like', models.IntegerField(default=0)),
                ('flag', models.IntegerField(default=0)),
                ('like_dislike_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dislike', to='MyApp.userdetailsmodel')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dislike', to='MyApp.codepostmodel')),
            ],
            options={
                'db_table': 'tbpost_likes_dislikes',
                'ordering': ('like_dislike_date',),
            },
        ),
        migrations.CreateModel(
            name='PostCommentReplys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_date', models.DateField()),
                ('reply_mesage', models.CharField(max_length=255)),
                ('comment_photo', models.CharField(max_length=255)),
                ('flag', models.IntegerField(default=0)),
                ('comment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentreplys', to='MyApp.postcomment')),
                ('reply_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentreplys', to='MyApp.userdetailsmodel')),
            ],
            options={
                'db_table': 'tblpost_comment_replys',
                'ordering': ('comment_photo',),
            },
        ),
        migrations.CreateModel(
            name='LikesSharesPostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_date', models.DateField()),
                ('flag', models.IntegerField(default=0)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postshare', to='MyApp.codepostmodel')),
                ('share_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postshare', to='MyApp.userdetailsmodel')),
            ],
            options={
                'db_table': 'post_shares_tbl',
                'ordering': ('share_date',),
            },
        ),
    ]
