# Generated by Django 4.2.1 on 2023-07-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0030_commentpostmodel_jobopeningsmodel_updatemodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetailsmodel',
            name='user_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
