# Generated by Django 4.2.1 on 2023-07-31 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0031_alter_userdetailsmodel_user_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentmodel',
            options={'ordering': ('id',)},
        ),
    ]
