# Generated by Django 4.2.1 on 2023-07-31 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0033_alter_admindetails_options_alter_citysmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topicsmodel',
            options={'ordering': ('id',)},
        ),
    ]
